pr40

diff --git a/.github/workflows/file.yml b/.github/workflows/file.yml
--- a/.github/workflows/file.yml
+++ b/.github/workflows/file.yml
@@ -23,32 +23,32 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v4
 
-      - name: Setup python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.12'
+      # - name: Setup python
+      #   uses: actions/setup-python@v5
+      #   with:
+      #     python-version: '3.12'
 
-      - name: Validate file creation
-        run: |
-          python ./example.py
-          if [ -f "file.txt" ]; then
-            echo "file.txt exists"
-          else
-            echo "file.txt does not exist"
-            echo "**Validation failed. Skipping PR creation and reviewer assignment.**"
-            exit 1  # Use a non-zero exit code to indicate failure, but don't prevent the push
-          fi
+      # - name: Validate file creation
+      #   run: |
+      #     python ./example.py
+      #     if [ -f "file.txt" ]; then
+      #       echo "file.txt exists"
+      #     else
+      #       echo "file.txt does not exist"
+      #       echo "**Validation failed. Skipping PR creation and reviewer assignment.**"
+      #       exit 1  # Use a non-zero exit code to indicate failure, but don't prevent the push
+      #     fi
 
-      - name: create pull request
-        run: |
-          pr_number=$(gh pr create -B main -H develop --title 'Merge develop into main' --body 'Created by GitHub Actions'| grep -oP '\/pull\/(\d+)'| sed 's/\/pull\///'); echo "PR number is $pr_number"; echo "::set-output name=pr_number::$pr_number"
-          echo "::set-output name=pr_number::$pr_number"
-          echo "PR_NUMBER={$pr_number}" >> $GITHUB_ENV
-          echo "PR number at moment of create pr is $pr_number"
-          echo "PR number at moment of create pr is $PR_NUMBER"
+      # - name: create pull request
+      #   run: |
+      #     pr_number=$(gh pr create -B main -H develop --title 'Merge develop into main' --body 'Created by GitHub Actions'| grep -oP '\/pull\/(\d+)'| sed 's/\/pull\///'); echo "PR number is $pr_number"; echo "::set-output name=pr_number::$pr_number"
+      #     echo "::set-output name=pr_number::$pr_number"
+      #     echo "PR_NUMBER={$pr_number}" >> $GITHUB_ENV
+      #     echo "PR number at moment of create pr is $pr_number"
+      #     echo "PR number at moment of create pr is $PR_NUMBER"
 
-        env:
-          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
 
       - name: Assign Random Reviewer
         run: |
